package com.mattiarubini.reminder.database;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

import com.mattiarubini.reminder.Utilities.DateManager;

import java.text.ParseException;
import java.util.Date;

@Entity(foreignKeys = @ForeignKey(entity = CategoryReminderEntity.class,
                                    parentColumns = "name",
                                    childColumns = "category"),
        indices = {@Index("category")})
public class ReminderEntity {

    // unsigned int, generated by the db
    @PrimaryKey(autoGenerate = true)
    @NonNull
    private int uid;

    @NonNull
    private String text;

    @NonNull
    private String trigger;

    @ColumnInfo(name = "category")
    private String category;

    /**
     * Constructor
     * */
    public ReminderEntity(String text, String trigger, String category){
        this.text = text;
        this.trigger = trigger;
    }

    public void setUid(int uid) {
        this.uid = uid;
    }

    public int getUid() {
        return uid;
    }

    public void setText(@NonNull String text) {
        this.text = text;
    }

    public String getText(){
        return text;
    }

    public void setTrigger(@NonNull String trigger) {
        this.trigger = trigger;
    }

    public String getTrigger() {
        return trigger;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategory(){
        return category;
    }

}
